---
- name: check connectivity
  ping:
    data: alive


- name: Create the required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0777"
  with_items:
    - /root/gitlab
    - /root/gitlab/config
    - /root/gitlab/logs
    - /root/gitlab/data



- name: Pull the gitlab image
  docker_image:
    name: gitlab/gitlab-ce:{{ gitlab_server_version }}
    source: pull


- name: Set the config file for gitlab container
  template:
    dest: /root/gitlab/config/gitlab.rb
    src: templates/gitlab.rb.j2
    mode: "0777"
  vars:
    external_url: "{{ external_url }}"



- name: Run the gitlab server container
  docker_container:
    name: "gitlab_server"
    image: gitlab/gitlab-ce:{{ gitlab_server_version }}
    restart_policy: unless-stopped
    state: started
    hostname: "{{ external_url }}"
    network_mode: host
    shm_size: '256m'
    volumes:
      - /root/gitlab/config:/etc/gitlab
      - /root/gitlab/logs:/var/log/gitlab
      - /root/gitlab/data:/var/opt/gitlab







